plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.example.devicepolicycontroller"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.example.devicepolicycontroller"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
    }
}

dependencies {
    // Resolves Android Studio Material template resources if values-night is regenerated by the IDE.
    implementation("com.google.android.material:material:1.12.0")
}
